openapi: 3.2.0
info:
  contact:
    email: support@akeyless.io
    name: Akeyless
    url: http://akeyless.io
  description: The purpose of this application is to provide access to Akeyless API.
  title: Akeyless Get Account Settings API
  version: '2.0'
servers:
- url: https://api.akeyless.io/
tags:
- name: Get Account Settings
paths:
  /get-account-settings:
    post:
      operationId: getAccountSettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getAccountSettings'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccountSettingsCommandOutput'
          description: getAccountSettingsResponse wraps response body.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONError'
          description: 'errorResponse wraps any error to return it as a JSON object with one "error"

            field.'
      tags:
      - Get Account Settings
      x-codegen-request-body-name: body
      summary: Get account settings
      x-summary-source: derived
components:
  schemas:
    DataProtectionSection:
      description: 'We need the fields to be pointers as we

        use the same struct for partial updates as well'
      example:
        enable_classic_key_protection: true
      properties:
        enable_classic_key_protection:
          type: boolean
          x-go-name: EnableClassicKeyProtection
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
    SmInfo:
      example:
        tier: tier
        sla: sla
      properties:
        sla:
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
        tier:
          description: 'Tier represents a level of extensibility the account will have, defined by various limits for different

            resources of Akeyless

            e.g - A StarterTier may have a limit of 3 Client resources and 50 Secret resources'
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client/commands
    PasswordPolicyInfo:
      example:
        use_numbers: true
        use_capital_letters: true
        use_special_characters: true
        use_lower_letters: true
        password_length: 6
      properties:
        password_length:
          format: int64
          type: integer
          x-go-name: PasswordLength
        use_capital_letters:
          type: boolean
          x-go-name: UseCapitalLetters
        use_lower_letters:
          type: boolean
          x-go-name: UseLowerLetters
        use_numbers:
          type: boolean
          x-go-name: UseNumbers
        use_special_characters:
          type: boolean
          x-go-name: UseSpecialCharacters
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
    CustomerFullAddress:
      example:
        country: country
        city: city
        street: street
        postal_code: postal_code
      properties:
        city:
          type: string
          x-go-name: City
        country:
          type: string
          x-go-name: Country
        postal_code:
          type: string
          x-go-name: PostalCode
        street:
          type: string
          x-go-name: Street
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
    JSONError:
      properties:
        error:
          type: string
          x-go-name: Err
      title: JSONError wraps an error with JSON object.
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client
    GetAccountSettingsCommandOutput:
      example:
        secure_remote_access:
          user_type: user_type
          tier: tier
          sla: sla
        account_id: account_id
        address:
          country: country
          city: city
          street: street
          postal_code: postal_code
        phone: phone
        company_name: company_name
        object_version_settings:
          default-versioning: true
          items:
          - item-type: item-type
            max-versions: max-versions
          - item-type: item-type
            max-versions: max-versions
        general_settings:
          password_policy:
            use_numbers: true
            use_capital_letters: true
            use_special_characters: true
            use_lower_letters: true
            password_length: 6
          data_protection_section:
            enable_classic_key_protection: true
          enable_request_for_access: true
        secret_management:
          tier: tier
          sla: sla
        system_access_creds_settings:
          jwt_ttl_maximum: 6
          jwt_ttl_minimum: 1
          jwt_ttl_default: 0
        email: email
      properties:
        account_id:
          type: string
          x-go-name: AccountID
        address:
          $ref: '#/components/schemas/CustomerFullAddress'
        company_name:
          type: string
          x-go-name: CompanyName
        email:
          type: string
          x-go-name: CustomerEmail
        general_settings:
          $ref: '#/components/schemas/AccountGeneralSettings'
        object_version_settings:
          $ref: '#/components/schemas/AccountObjectVersionSettingsOutput'
        phone:
          type: string
          x-go-name: CustomerPhone
        secret_management:
          $ref: '#/components/schemas/SmInfo'
        secure_remote_access:
          $ref: '#/components/schemas/SraInfo'
        system_access_creds_settings:
          $ref: '#/components/schemas/SystemAccessCredsSettings'
      title: GetAccountSettingsCommandOutput defines cli output of get-account-settings command.
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client/commands
    ObjectVersionSettingsOutput:
      example:
        item-type: item-type
        max-versions: max-versions
      properties:
        item-type:
          description: VersionSettingsObjectType defines object types for account version settings
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
        max-versions:
          type: string
          x-go-name: MaxVersions
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client/commands
    SystemAccessCredsSettings:
      description: SystemAccessCredsSettings describes system access credential settings for account by minutes
      example:
        jwt_ttl_maximum: 6
        jwt_ttl_minimum: 1
        jwt_ttl_default: 0
      properties:
        jwt_ttl_default:
          format: int64
          type: integer
          x-go-name: JwtTtlDefault
        jwt_ttl_maximum:
          format: int64
          type: integer
          x-go-name: JwtTtlMaximum
        jwt_ttl_minimum:
          format: int64
          type: integer
          x-go-name: JwtTtlMinimum
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
    AccountGeneralSettings:
      description: AccountGeneralSettings describes general settings for an account
      example:
        password_policy:
          use_numbers: true
          use_capital_letters: true
          use_special_characters: true
          use_lower_letters: true
          password_length: 6
        data_protection_section:
          enable_classic_key_protection: true
        enable_request_for_access: true
      properties:
        data_protection_section:
          $ref: '#/components/schemas/DataProtectionSection'
        enable_request_for_access:
          type: boolean
          x-go-name: EnableRequestForAccess
        password_policy:
          $ref: '#/components/schemas/PasswordPolicyInfo'
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
    SraInfo:
      example:
        user_type: user_type
        tier: tier
        sla: sla
      properties:
        sla:
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
        tier:
          description: 'Tier represents a level of extensibility the account will have, defined by various limits for different

            resources of Akeyless

            e.g - A StarterTier may have a limit of 3 Client resources and 50 Secret resources'
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
        user_type:
          type: string
          x-go-name: UserType
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client/commands
    getAccountSettings:
      properties:
        json:
          description: Set output format to JSON
          type: boolean
          x-go-name: Json
        token:
          description: Authentication token (see `/auth` and `/configure`)
          type: string
          x-go-name: Profile
        uid-token:
          description: The universal identity token, Required only for universal_identity authentication
          type: string
          x-go-name: UIDToken
      title: getAccountSettings is a command that returns account settings.
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client/commands
    AccountObjectVersionSettingsOutput:
      example:
        default-versioning: true
        items:
        - item-type: item-type
          max-versions: max-versions
        - item-type: item-type
          max-versions: max-versions
      properties:
        default-versioning:
          type: boolean
          x-go-name: CreateNewVersionByDefault
        items:
          items:
            $ref: '#/components/schemas/ObjectVersionSettingsOutput'
          type: array
          x-go-name: ObjectSettings
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client/commands
