openapi: 3.2.0
info:
  contact:
    email: support@akeyless.io
    name: Akeyless
    url: http://akeyless.io
  description: The purpose of this application is to provide access to Akeyless API.
  title: Akeyless Gateway Update Producer Cassandra API
  version: '2.0'
servers:
- url: https://api.akeyless.io/
tags:
- name: Gateway Update Producer Cassandra
paths:
  /gateway-update-producer-cassandra:
    post:
      operationId: gatewayUpdateProducerCassandra
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/gatewayUpdateProducerCassandra'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewayUpdateProducerCassandraOutput'
          description: gatewayUpdateProducerCassandraResponse wraps response body.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONError'
          description: 'errorResponse wraps any error to return it as a JSON object with one "error"

            field.'
      tags:
      - Gateway Update Producer Cassandra
      x-codegen-request-body-name: body
      summary: Gateway update producer cassandra
      x-summary-source: derived
components:
  schemas:
    SecureRemoteAccess:
      example:
        schema: schema
        web_proxy: true
        bastion_ssh: bastion_ssh
        isolated: true
        ssh_private_key: true
        allow_port_forwarding: true
        is_web: true
        endpoint: endpoint
        native: true
        enable: true
        host:
        - host
        - host
        dashboard_url: dashboard_url
        bastion_issuer: bastion_issuer
        ssh_user: ssh_user
        is_cli: true
        use_internal_bastion: true
        rdp_user: rdp_user
        url: url
        account_id: account_id
        db_name: db_name
        allow_providing_external_username: true
        domain: domain
        bastion_api: bastion_api
        rotate_after_disconnect: true
        category: category
        region: region
        ssh_password: true
        bastion_issuer_id: 9
      properties:
        account_id:
          type: string
          x-go-name: AwsAccountId
        allow_port_forwarding:
          type: boolean
          x-go-name: K8SAllowPortForwading
        allow_providing_external_username:
          type: boolean
          x-go-name: AllowProvidingExternalUser
        bastion_api:
          type: string
          x-go-name: BastionAPI
        bastion_issuer:
          type: string
          x-go-name: BastionIssuer
        bastion_issuer_id:
          format: int64
          type: integer
          x-go-name: BastionIssuerID
        bastion_ssh:
          type: string
          x-go-name: BastionSSH
        category:
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
        dashboard_url:
          type: string
          x-go-name: K8SDashboardURL
        db_name:
          type: string
          x-go-name: DbName
        domain:
          type: string
          x-go-name: RDPDomain
        enable:
          type: boolean
          x-go-name: Enable
        endpoint:
          type: string
          x-go-name: K8SEndpoint
        host:
          items:
            type: string
          type: array
          x-go-name: Host
        is_cli:
          type: boolean
          x-go-name: AccessCliCategory
        is_web:
          type: boolean
          x-go-name: AccessWebCategory
        isolated:
          type: boolean
          x-go-name: Isolated
        native:
          type: boolean
          x-go-name: AwsNativeCli
        rdp_user:
          type: string
          x-go-name: RDPUser
        region:
          type: string
          x-go-name: AwsRegion
        rotate_after_disconnect:
          type: boolean
          x-go-name: RotateAfterDisconnect
        schema:
          type: string
          x-go-name: Schema
        ssh_password:
          type: boolean
          x-go-name: SSHPassword
        ssh_private_key:
          type: boolean
          x-go-name: SSHPrivateKey
        ssh_user:
          type: string
          x-go-name: SSHUser
        url:
          type: string
          x-go-name: URL
        use_internal_bastion:
          type: boolean
          x-go-name: UseInternalBastion
        web_proxy:
          type: boolean
          x-go-name: WebProxy
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
    DSProducerDetails:
      example:
        gke_cluster_endpoint: gke_cluster_endpoint
        dynamic_secret_type: dynamic_secret_type
        metadata: metadata
        last_admin_rotation: 9
        db_max_open_conns: db_max_open_conns
        admin_rotation_interval_days: 0
        ssl_connection_certificate: ssl_connection_certificate
        oracle_creation_statements: oracle_creation_statements
        mssql_creation_statements: mssql_creation_statements
        password: password
        sf_user_role: sf_user_role
        privileged_user: privileged_user
        ldap_certificate: ldap_certificate
        gcp_role_bindings:
          key:
          - gcp_role_bindings
          - gcp_role_bindings
        ldap_url: ldap_url
        username_policy: username_policy
        gcp_token_scope: gcp_token_scope
        venafi_allowed_domains:
        - venafi_allowed_domains
        - venafi_allowed_domains
        warn_before_user_expiration_min: 1
        db_private_key: db_private_key
        fixed_user_only: fixed_user_only
        rabbitmq_server_password: rabbitmq_server_password
        aws_user_policies: aws_user_policies
        aws_role_arns: aws_role_arns
        active: true
        item_targets_assoc:
        - assoc_id: assoc_id
          target_name: target_name
          target_type: target_type
          attributes:
            key: attributes
          target_id: 6
        - assoc_id: assoc_id
          target_name: target_name
          target_type: target_type
          attributes:
            key: attributes
          target_id: 6
        chef_server_username: chef_server_username
        tags:
        - tags
        - tags
        mongodb_custom_data: mongodb_custom_data
        k8s_service_account: k8s_service_account
        chef_skip_ssl: true
        k8s_cluster_endpoint: k8s_cluster_endpoint
        azure_client_secret: azure_client_secret
        azure_user_groups_obj_id: azure_user_groups_obj_id
        gcp_token_type: gcp_token_type
        access_token_manager_id: access_token_manager_id
        gcp_token_lifetime: gcp_token_lifetime
        user_name: user_name
        rabbitmq_user_vhost: rabbitmq_user_vhost
        mongodb_username: mongodb_username
        postgres_revocation_statements: postgres_revocation_statements
        venafi_signer_key_name: venafi_signer_key_name
        should_stop: should_stop
        artifactory_token_audience: artifactory_token_audience
        mongodb_atlas_api_public_key: mongodb_atlas_api_public_key
        github_installation_token_permissions:
          key: github_installation_token_permissions
        timeout_seconds: 4
        eks_assume_role: eks_assume_role
        db_max_idle_conns: db_max_idle_conns
        admin_name: admin_name
        rabbitmq_server_user: rabbitmq_server_user
        venafi_api_key: venafi_api_key
        mongodb_host_port: mongodb_host_port
        gke_cluster_ca_certificate: gke_cluster_ca_certificate
        k8s_bearer_token: k8s_bearer_token
        azure_resource_name: azure_resource_name
        cassandra_creation_statements: cassandra_creation_statements
        failure_message: failure_message
        db_private_key_passphrase: db_private_key_passphrase
        rabbitmq_user_read_permission: rabbitmq_user_read_permission
        azure_client_id: azure_client_id
        mongodb_default_auth_db: mongodb_default_auth_db
        mongodb_atlas_project_id: mongodb_atlas_project_id
        payload: payload
        redshift_creation_statements: redshift_creation_statements
        enforce_replay_prevention: true
        ldap_audience: ldap_audience
        redirect_uris:
        - redirect_uris
        - redirect_uris
        venafi_allow_subdomains: true
        aws_user_console_access: true
        azure_resource_group_name: azure_resource_group_name
        user_principal_name: user_principal_name
        azure_subscription_id: azure_subscription_id
        gcp_key_algo: gcp_key_algo
        venafi_zone: venafi_zone
        github_installation_token_repositories:
        - github_installation_token_repositories
        - github_installation_token_repositories
        gcp_service_account_key: gcp_service_account_key
        gcp_service_account_type: gcp_service_account_type
        session_extension_warn_interval_min: 2
        venafi_store_private_key: true
        eks_cluster_endpoint: eks_cluster_endpoint
        gke_service_account_key: gke_service_account_key
        mongodb_uri_options: mongodb_uri_options
        github_app_private_key: github_app_private_key
        gke_service_account_name: gke_service_account_name
        mysql_creation_statements: mysql_creation_statements
        github_installation_id: 5
        k8s_allowed_namespaces: k8s_allowed_namespaces
        rabbitmq_server_uri: rabbitmq_server_uri
        chef_server_access_mode: chef_server_access_mode
        rabbitmq_user_conf_permission: rabbitmq_user_conf_permission
        is_fixed_user: is_fixed_user
        sf_account: sf_account
        secure_remote_access_details:
          schema: schema
          web_proxy: true
          bastion_ssh: bastion_ssh
          isolated: true
          ssh_private_key: true
          allow_port_forwarding: true
          is_web: true
          endpoint: endpoint
          native: true
          enable: true
          host:
          - host
          - host
          dashboard_url: dashboard_url
          bastion_issuer: bastion_issuer
          ssh_user: ssh_user
          is_cli: true
          use_internal_bastion: true
          rdp_user: rdp_user
          url: url
          account_id: account_id
          db_name: db_name
          allow_providing_external_username: true
          domain: domain
          bastion_api: bastion_api
          rotate_after_disconnect: true
          category: category
          region: region
          ssh_password: true
          bastion_issuer_id: 9
        chef_server_host_name: chef_server_host_name
        k8s_role_type: k8s_role_type
        mongodb_is_atlas: true
        eks_cluster_ca_certificate: eks_cluster_ca_certificate
        rotate_sync_url: rotate_sync_url
        chef_server_url: chef_server_url
        aws_user_groups: aws_user_groups
        azure_tenant_id: azure_tenant_id
        jwks_url: jwks_url
        k8s_namespace: k8s_namespace
        user_password: user_password
        venafi_sign_using_akeyless_pki: true
        dynamic_secret_key: dynamic_secret_key
        chef_server_key: chef_server_key
        implementation_type: implementation_type
        gcp_tmp_service_account_name: gcp_tmp_service_account_name
        issuer: issuer
        github_app_id: 1
        ldap_bind_dn: ldap_bind_dn
        k8s_temp_role_definition:
        - 7
        - 7
        admin_pwd: admin_pwd
        azure_fixed_user_only: true
        azure_user_roles_template_id: azure_user_roles_template_id
        aws_access_mode: aws_access_mode
        username_length: 7
        authorization_port: authorization_port
        db_host_name: db_host_name
        ldap_user_dn: ldap_user_dn
        azure_fixed_user_name_sub_claim_key: azure_fixed_user_name_sub_claim_key
        delete_protection: true
        db_name: db_name
        k8s_role_name: k8s_role_name
        db_port: db_port
        artifactory_base_url: artifactory_base_url
        create_sync_url: create_sync_url
        aws_session_token: aws_session_token
        jwks: jwks
        hanadb_revocation_statements: hanadb_revocation_statements
        db_isolation_level: db_isolation_level
        ssl_connection_mode: true
        mongodb_roles: mongodb_roles
        mongodb_db_name: mongodb_db_name
        eks_access_key_id: eks_access_key_id
        venafi_base_url: venafi_base_url
        user_ttl: user_ttl
        ping_url: ping_url
        ldap_token_expiration: ldap_token_expiration
        venafi_use_tpp: true
        mongodb_password: mongodb_password
        aws_secret_access_key: aws_secret_access_key
        mongodb_atlas_api_private_key: mongodb_atlas_api_private_key
        postgres_creation_statements: postgres_creation_statements
        password_policy: password_policy
        artifactory_admin_username: artifactory_admin_username
        restricted_scopes:
        - restricted_scopes
        - restricted_scopes
        scopes:
        - scopes
        - scopes
        sf_warehouse_name: sf_warehouse_name
        artifactory_token_scope: artifactory_token_scope
        k8s_dynamic_mode: true
        revoke_sync_url: revoke_sync_url
        host_port: host_port
        enable_admin_rotation: true
        client_authentication_type: client_authentication_type
        mongodb_uri_connection: mongodb_uri_connection
        db_user_name: db_user_name
        eks_region: eks_region
        artifactory_admin_apikey: artifactory_admin_apikey
        azure_app_object_id: azure_app_object_id
        ldap_bind_password: ldap_bind_password
        subject_dn: subject_dn
        externally_provided_user: externally_provided_user
        db_server_certificates: db_server_certificates
        db_server_name: db_server_name
        venafi_tpp_username: venafi_tpp_username
        azure_user_portal_access: true
        venafi_root_first_in_chain: true
        venafi_auto_generated_folder: venafi_auto_generated_folder
        db_pwd: db_pwd
        signing_algorithm: signing_algorithm
        administrative_port: administrative_port
        github_installation_token_repositories_ids:
        - 5
        - 5
        gcp_service_account_email: gcp_service_account_email
        hanadb_creation_statements: hanadb_creation_statements
        password_length: 3
        dynamic_secret_name: dynamic_secret_name
        aws_user_programmatic_access: true
        rabbitmq_user_write_permission: rabbitmq_user_write_permission
        rabbitmq_user_tags: rabbitmq_user_tags
        venafi_tpp_password: venafi_tpp_password
        ldap_user_attr: ldap_user_attr
        use_gw_cloud_identity: true
        azure_user_programmatic_access: true
        k8s_cluster_ca_certificate: k8s_cluster_ca_certificate
        eks_secret_access_key: eks_secret_access_key
        grant_types:
        - grant_types
        - grant_types
        github_base_url: github_base_url
        groups: groups
        chef_organizations: chef_organizations
        dynamic_secret_id: 6
        mssql_revocation_statements: mssql_revocation_statements
        chef_server_port: chef_server_port
        github_repository_path: github_repository_path
        aws_access_key_id: aws_access_key_id
        aws_region: aws_region
        eks_cluster_name: eks_cluster_name
        gke_cluster_name: gke_cluster_name
        k8s_temp_role_binding_definition:
        - 2
        - 2
        host_name: host_name
      properties:
        access_token_manager_id:
          type: string
          x-go-name: AccessTokenManagerId
        active:
          type: boolean
          x-go-name: Active
        admin_name:
          type: string
          x-go-name: AdminName
        admin_pwd:
          type: string
          x-go-name: AdminPwd
        admin_rotation_interval_days:
          format: int64
          type: integer
          x-go-name: RotationIntervalDays
        administrative_port:
          type: string
          x-go-name: AdministrativePort
        artifactory_admin_apikey:
          type: string
          x-go-name: ArtifactoryAdminApiKey
        artifactory_admin_username:
          type: string
          x-go-name: ArtifactoryAdminUsername
        artifactory_base_url:
          type: string
          x-go-name: ArtifactoryBaseURL
        artifactory_token_audience:
          type: string
          x-go-name: ArtifactoryTokenAudience
        artifactory_token_scope:
          type: string
          x-go-name: ArtifactoryTokenScope
        authorization_port:
          type: string
          x-go-name: AuthorizationPort
        aws_access_key_id:
          type: string
          x-go-name: AWSAccessKeyID
        aws_access_mode:
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/producer/config
        aws_region:
          type: string
          x-go-name: AWSRegion
        aws_role_arns:
          type: string
          x-go-name: AWSRoleARNs
        aws_secret_access_key:
          type: string
          x-go-name: AWSSecretAccessKey
        aws_session_token:
          type: string
          x-go-name: AWSSessionToken
        aws_user_console_access:
          type: boolean
          x-go-name: AWSUserConsoleAccess
        aws_user_groups:
          type: string
          x-go-name: AWSUserGroups
        aws_user_policies:
          type: string
          x-go-name: AWSUserPolicies
        aws_user_programmatic_access:
          type: boolean
          x-go-name: AWSUserProgAccess
        azure_app_object_id:
          type: string
          x-go-name: AzureAppObjectID
        azure_client_id:
          type: string
          x-go-name: AzureClientID
        azure_client_secret:
          type: string
          x-go-name: AzureClientSecret
        azure_fixed_user_name_sub_claim_key:
          type: string
          x-go-name: AzureFixedUserNameSubClaimKey
        azure_fixed_user_only:
          type: boolean
          x-go-name: AzureFixedUserOnly
        azure_resource_group_name:
          type: string
          x-go-name: AzureResourceGroupName
        azure_resource_name:
          type: string
          x-go-name: AzureResourceName
        azure_subscription_id:
          type: string
          x-go-name: AzureSubscriptionId
        azure_tenant_id:
          type: string
          x-go-name: AzureTenantID
        azure_user_groups_obj_id:
          type: string
          x-go-name: AzureUserGroupsObjID
        azure_user_portal_access:
          type: boolean
          x-go-name: AzureUserConsoleAccess
        azure_user_programmatic_access:
          type: boolean
          x-go-name: AzureUserProgAccess
        azure_user_roles_template_id:
          type: string
          x-go-name: AzureUserRolesTemplateID
        cassandra_creation_statements:
          type: string
          x-go-name: CassandraCreationStatements
        chef_organizations:
          type: string
          x-go-name: ChefOrganizations
        chef_server_access_mode:
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/producer/config
        chef_server_host_name:
          type: string
          x-go-name: ChefServerHostName
        chef_server_key:
          type: string
          x-go-name: ChefServerKey
        chef_server_port:
          type: string
          x-go-name: ChefServerPort
        chef_server_url:
          type: string
          x-go-name: ChefServerURL
        chef_server_username:
          type: string
          x-go-name: ChefServerUsername
        chef_skip_ssl:
          type: boolean
          x-go-name: ChefSkipSSL
        client_authentication_type:
          type: string
          x-go-name: ClientAuthenticationType
        create_sync_url:
          type: string
          x-go-name: CreateSyncURL
        db_host_name:
          type: string
          x-go-name: DbHostName
        db_isolation_level:
          type: string
          x-go-name: DbIsolationLevel
        db_max_idle_conns:
          type: string
          x-go-name: DbMaxIdleConns
        db_max_open_conns:
          type: string
          x-go-name: DbMaxOpenConns
        db_name:
          type: string
          x-go-name: DbName
        db_port:
          type: string
          x-go-name: DbPort
        db_private_key:
          description: (Optional) Private Key in PEM format
          type: string
          x-go-name: DbPrivateKey
        db_private_key_passphrase:
          type: string
          x-go-name: DbPrivateKeyPassphrase
        db_pwd:
          type: string
          x-go-name: DbPwd
        db_server_certificates:
          description: '(Optional) DBServerCertificates defines the set of root certificate authorities

            that clients use when verifying server certificates.

            If DBServerCertificates is empty, TLS uses the host''s root CA set.'
          type: string
          x-go-name: DBServerCertificates
        db_server_name:
          description: '(Optional) ServerName is used to verify the hostname on the returned

            certificates unless InsecureSkipVerify is given. It is also included

            in the client''s handshake to support virtual hosting unless it is

            an IP address.'
          type: string
          x-go-name: DBServerName
        db_user_name:
          type: string
          x-go-name: DbUserName
        delete_protection:
          type: boolean
          x-go-name: ItemProtected
        dynamic_secret_id:
          format: int64
          type: integer
          x-go-name: DynamicSecretId
        dynamic_secret_key:
          type: string
          x-go-name: ProtectionKeyName
        dynamic_secret_name:
          type: string
          x-go-name: DynamicSecretName
        dynamic_secret_type:
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/producer
        eks_access_key_id:
          type: string
          x-go-name: EKSAccessID
        eks_assume_role:
          type: string
          x-go-name: EKSAssumeRole
        eks_cluster_ca_certificate:
          type: string
          x-go-name: EKSClusterCACertificate
        eks_cluster_endpoint:
          type: string
          x-go-name: EKSClusterEndpoint
        eks_cluster_name:
          type: string
          x-go-name: EKSClusterName
        eks_region:
          type: string
          x-go-name: EKSRegion
        eks_secret_access_key:
          type: string
          x-go-name: EKSSecretAccessKey
        enable_admin_rotation:
          type: boolean
          x-go-name: EnableAdminRotation
        enforce_replay_prevention:
          description: relevant for PRIVATE_KEY_JWT client authentication type
          type: boolean
          x-go-name: EnforceReplayPrevention
        externally_provided_user:
          type: string
          x-go-name: ExternallyProvidedUser
        failure_message:
          type: string
          x-go-name: FailureMessage
        fixed_user_only:
          type: string
          x-go-name: FixedUserOnly
        gcp_key_algo:
          type: string
          x-go-name: GCPKeyAlgorithm
        gcp_role_bindings:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
          x-go-name: GCPRoleBindings
        gcp_service_account_email:
          description: GCPServiceAccountEmail overrides the deprecated field from the target
          type: string
          x-go-name: GCPServiceAccountEmail
        gcp_service_account_key:
          type: string
          x-go-name: GCPServiceAccountKey
        gcp_service_account_type:
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/producer/config
        gcp_tmp_service_account_name:
          type: string
          x-go-name: GCPTmpServiceAccountName
        gcp_token_lifetime:
          type: string
          x-go-name: GCPTokenLifetime
        gcp_token_scope:
          type: string
          x-go-name: GCPTokenScopes
        gcp_token_type:
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/producer/config
        github_app_id:
          format: int64
          type: integer
          x-go-name: GithubAppId
        github_app_private_key:
          type: string
          x-go-name: GithubAppPrivateKey
        github_base_url:
          type: string
          x-go-name: GithubBaseURL
        github_installation_id:
          format: int64
          type: integer
          x-go-name: GithubInstallationId
        github_installation_token_permissions:
          additionalProperties:
            type: string
          type: object
          x-go-name: GithubTokenPermissions
        github_installation_token_repositories:
          items:
            type: string
          type: array
          x-go-name: GithubTokenRepositories
        github_installation_token_repositories_ids:
          items:
            format: int64
            type: integer
          type: array
          x-go-name: GithubTokenRepositoriesById
        github_repository_path:
          type: string
          x-go-name: GithubRepositoryPath
        gke_cluster_ca_certificate:
          type: string
          x-go-name: GKEClusterCACertificate
        gke_cluster_endpoint:
          type: string
          x-go-name: GKEClusterEndpoint
        gke_cluster_name:
          type: string
          x-go-name: GKEClusterName
        gke_service_account_key:
          type: string
          x-go-name: GKEServiceAccountKey
        gke_service_account_name:
          type: string
          x-go-name: GKEServiceAccountName
        grant_types:
          items:
            type: string
          type: array
          x-go-name: GrantTypes
        groups:
          type: string
          x-go-name: Groups
        hanadb_creation_statements:
          type: string
          x-go-name: HanaDbCreationStatements
        hanadb_revocation_statements:
          type: string
          x-go-name: HanaDbRevocationStatements
        host_name:
          type: string
          x-go-name: HostName
        host_port:
          type: string
          x-go-name: HostPort
        implementation_type:
          type: string
          x-go-name: ImplementationType
        is_fixed_user:
          type: string
          x-go-name: IsFixedUser
        issuer:
          description: relevant for CLIENT_TLS_CERTIFICATE client authentication type
          type: string
          x-go-name: Issuer
        item_targets_assoc:
          items:
            $ref: '#/components/schemas/ItemTargetAssociation'
          type: array
          x-go-name: ItemTargetsAssoc
        jwks:
          type: string
          x-go-name: JWKs
        jwks_url:
          type: string
          x-go-name: JWKsURL
        k8s_allowed_namespaces:
          description: comma-separated list of allowed namespaces. Can hold just * which signifies that any namespace is allowed
          type: string
          x-go-name: AllowedNamespaces
        k8s_bearer_token:
          type: string
          x-go-name: K8sBearerToken
        k8s_cluster_ca_certificate:
          type: string
          x-go-name: K8sClusterCACertificate
        k8s_cluster_endpoint:
          type: string
          x-go-name: K8sClusterEndpoint
        k8s_dynamic_mode:
          description: 'when native k8s is in dynamic mode, user can define allowed namespaces,

            K8sServiceAccount doesn''t exist from the start and will only be created at time of getting dynamic secret value

            By default dynamic mode is false and producer behaves like it did before'
          type: boolean
          x-go-name: DynamicMode
        k8s_namespace:
          type: string
          x-go-name: K8sNamespace
        k8s_role_name:
          description: Name of the pre-existing Role or ClusterRole to bind a generated service account to.
          type: string
          x-go-name: K8sRoleName
        k8s_role_type:
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/producer/config
        k8s_service_account:
          type: string
          x-go-name: K8sServiceAccount
        k8s_temp_role_binding_definition:
          description: 'Yaml/Json definition of temporary role binding that will be created and deleted when TTL is due.

            Must have as subject name of Service Account specified in K8sServiceAccount field'
          items:
            format: uint8
            type: integer
          type: array
          x-go-name: K8sTempRoleBindingDefinition
        k8s_temp_role_definition:
          description: Yaml/Json definition of temporary role that will be created and deleted when TTL is due
          items:
            format: uint8
            type: integer
          type: array
          x-go-name: K8sTempRoleDefinition
        last_admin_rotation:
          format: int64
          type: integer
          x-go-name: LastAdminRotation
        ldap_audience:
          type: string
          x-go-name: Audience
        ldap_bind_dn:
          type: string
          x-go-name: BindDn
        ldap_bind_password:
          type: string
          x-go-name: BindPass
        ldap_certificate:
          type: string
          x-go-name: Certificate
        ldap_token_expiration:
          type: string
          x-go-name: TokenExpirationInSec
        ldap_url:
          type: string
          x-go-name: Url
        ldap_user_attr:
          type: string
          x-go-name: UserAttr
        ldap_user_dn:
          type: string
          x-go-name: UserDn
        metadata:
          type: string
          x-go-name: Metadata
        mongodb_atlas_api_private_key:
          type: string
          x-go-name: MongoDBAtlasAPIPrivateKey
        mongodb_atlas_api_public_key:
          type: string
          x-go-name: MongoDBAtlasAPIPublicKey
        mongodb_atlas_project_id:
          description: mongodb atlas fields
          type: string
          x-go-name: MongoDBAtlasProjectID
        mongodb_custom_data:
          type: string
          x-go-name: MongoDBCustomData
        mongodb_db_name:
          description: common fields
          type: string
          x-go-name: MongoDBName
        mongodb_default_auth_db:
          type: string
          x-go-name: MongoDBDefaultAuthDB
        mongodb_host_port:
          type: string
          x-go-name: MongoDBHostAndPort
        mongodb_is_atlas:
          type: boolean
          x-go-name: MongoDBAtlas
        mongodb_password:
          type: string
          x-go-name: MongoDBPassword
        mongodb_roles:
          description: common fields
          type: string
          x-go-name: MongoDBRoles
        mongodb_uri_connection:
          description: mongodb fields
          type: string
          x-go-name: MongoDBServerURI
        mongodb_uri_options:
          type: string
          x-go-name: MongoDBURIOptions
        mongodb_username:
          type: string
          x-go-name: MongoDBUsername
        mssql_creation_statements:
          type: string
          x-go-name: MSSQLCreationStatements
        mssql_revocation_statements:
          type: string
          x-go-name: MSSQLRevocationStatements
        mysql_creation_statements:
          type: string
          x-go-name: MysqlCreationStatements
        oracle_creation_statements:
          type: string
          x-go-name: OracleDBCreationStatements
        password:
          type: string
          x-go-name: Password
        password_length:
          format: int64
          type: integer
          x-go-name: PasswordLen
        password_policy:
          type: string
          x-go-name: PasswordPolicy
        payload:
          type: string
          x-go-name: Payload
        ping_url:
          type: string
          x-go-name: PingURL
        postgres_creation_statements:
          type: string
          x-go-name: PostgresCreationStatements
        postgres_revocation_statements:
          type: string
          x-go-name: PostgresRevocationStatements
        privileged_user:
          type: string
          x-go-name: PrivilegedUser
        rabbitmq_server_password:
          type: string
          x-go-name: RabbitmqServerPassword
        rabbitmq_server_uri:
          type: string
          x-go-name: RabbitmqServerURI
        rabbitmq_server_user:
          type: string
          x-go-name: RabbitmqServerUser
        rabbitmq_user_conf_permission:
          type: string
          x-go-name: RabbitmqUserConfigPermission
        rabbitmq_user_read_permission:
          type: string
          x-go-name: RabbitmqUserReadPermission
        rabbitmq_user_tags:
          type: string
          x-go-name: RabbitmqUserTags
        rabbitmq_user_vhost:
          type: string
          x-go-name: RabbitmqUserVHost
        rabbitmq_user_write_permission:
          type: string
          x-go-name: RabbitmqUserWritePermission
        redirect_uris:
          items:
            type: string
          type: array
          x-go-name: RedirectUris
        redshift_creation_statements:
          type: string
          x-go-name: RedshiftCreationStatements
        restricted_scopes:
          items:
            type: string
          type: array
          x-go-name: RestrictedScopes
        revoke_sync_url:
          type: string
          x-go-name: RevokeSyncURL
        rotate_sync_url:
          type: string
          x-go-name: RotateSyncURL
        scopes:
          items:
            type: string
          type: array
          x-go-name: DockerhubScopes
        secure_remote_access_details:
          $ref: '#/components/schemas/SecureRemoteAccess'
        session_extension_warn_interval_min:
          format: int64
          type: integer
          x-go-name: SessionExtensionWarnIntervalInMin
        sf_account:
          type: string
          x-go-name: SnowflakeAccountName
        sf_user_role:
          description: generated  users info
          type: string
          x-go-name: SnowflakeUserRole
        sf_warehouse_name:
          type: string
          x-go-name: SnowflakeWarehouseName
        should_stop:
          description: TODO delete this after migration
          type: string
          x-go-name: ShouldStop
        signing_algorithm:
          type: string
          x-go-name: SigningAlgorithm
        ssl_connection_certificate:
          description: (Optional) SSLConnectionCertificate defines the certificate for SSL connection. Must be base64 certificate loaded by UI using file loader field
          type: string
          x-go-name: SSLConnectionCertificate
        ssl_connection_mode:
          description: (Optional) SSLConnectionMode defines if SSL mode will be used to connect to DB
          type: boolean
          x-go-name: SSLConnectionMode
        subject_dn:
          type: string
          x-go-name: SubjectDN
        tags:
          items:
            type: string
          type: array
          x-go-name: Tags
        timeout_seconds:
          format: int64
          type: integer
          x-go-name: TimeoutSeconds
        use_gw_cloud_identity:
          type: boolean
          x-go-name: EKSUseDefaultIdentity
        user_name:
          type: string
          x-go-name: UserName
        user_password:
          type: string
          x-go-name: UserPassword
        user_principal_name:
          type: string
          x-go-name: AzurePrincipalName
        user_ttl:
          type: string
          x-go-name: UserTtl
        username_length:
          format: int64
          type: integer
          x-go-name: UsernameLen
        username_policy:
          type: string
          x-go-name: UsernamePolicy
        venafi_allow_subdomains:
          type: boolean
          x-go-name: VenafiAllowSubdomains
        venafi_allowed_domains:
          items:
            type: string
          type: array
          x-go-name: VenafiAllowedDomains
        venafi_api_key:
          type: string
          x-go-name: VenafiApiKey
        venafi_auto_generated_folder:
          type: string
          x-go-name: VenafiAutoGeneratedFolder
        venafi_base_url:
          type: string
          x-go-name: VenafiBaseURL
        venafi_root_first_in_chain:
          type: boolean
          x-go-name: VenafiRootFirstInChain
        venafi_sign_using_akeyless_pki:
          type: boolean
          x-go-name: VenafiSignUsingAkeylessPKI
        venafi_signer_key_name:
          type: string
          x-go-name: VenafiSignerKeyName
        venafi_store_private_key:
          type: boolean
          x-go-name: VenafiStorePrivateKey
        venafi_tpp_password:
          type: string
          x-go-name: VenafiTPPPassword
        venafi_tpp_username:
          type: string
          x-go-name: VenafiTPPUserName
        venafi_use_tpp:
          type: boolean
          x-go-name: VenafiUseTPP
        venafi_zone:
          type: string
          x-go-name: VenafiZone
        warn_before_user_expiration_min:
          format: int64
          type: integer
          x-go-name: WarnBeforeUserExpirationInMin
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/producer/config
    JSONError:
      properties:
        error:
          type: string
          x-go-name: Err
      title: JSONError wraps an error with JSON object.
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client
    gatewayUpdateProducerCassandra:
      description: gatewayUpdateProducerCassandra is a command that updates a Cassandra producer
      properties:
        cassandra-creation-statements:
          description: Cassandra creation statements
          type: string
          x-go-name: CreationStatements
        cassandra-hosts:
          description: Cassandra hosts IP or addresses, comma separated
          type: string
          x-go-name: Host
        cassandra-password:
          description: Cassandra superuser password
          type: string
          x-go-name: Password
        cassandra-port:
          default: '9042'
          description: Cassandra port
          type: string
          x-go-name: Port
        cassandra-username:
          description: Cassandra superuser username
          type: string
          x-go-name: UserName
        delete_protection:
          description: Protection from accidental deletion of this item
          type: string
          x-go-name: ItemProtected
        json:
          description: Set output format to JSON
          type: boolean
          x-go-name: Json
        name:
          description: Producer name
          type: string
          x-go-name: ProducerName
        new-name:
          description: Producer name
          type: string
          x-go-name: ProducerNewName
        producer-encryption-key-name:
          description: Dynamic producer encryption key
          type: string
          x-go-name: ProducerEncryptionKey
        tags:
          description: List of the tags attached to this secret
          items:
            type: string
          type: array
          x-go-name: Tags
        target-name:
          description: Target name
          type: string
          x-go-name: TargetName
        token:
          description: Authentication token (see `/auth` and `/configure`)
          type: string
          x-go-name: Profile
        uid-token:
          description: The universal identity token, Required only for universal_identity authentication
          type: string
          x-go-name: UIDToken
        user-ttl:
          default: 60m
          description: User TTL
          type: string
          x-go-name: UserTtl
      required:
      - name
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client/commands
    ItemTargetAssociation:
      description: 'ItemTargetAssociation includes details of an association between an item

        and a target.'
      example:
        assoc_id: assoc_id
        target_name: target_name
        target_type: target_type
        attributes:
          key: attributes
        target_id: 6
      properties:
        assoc_id:
          type: string
          x-go-name: AssociationID
        attributes:
          additionalProperties:
            type: string
          type: object
          x-go-name: Attributes
        target_id:
          format: int64
          type: integer
          x-go-name: TargetID
        target_name:
          type: string
          x-go-name: TargetName
        target_type:
          type: string
          x-go-name: TargetType
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
    gatewayUpdateProducerCassandraOutput:
      example:
        producer_details:
          gke_cluster_endpoint: gke_cluster_endpoint
          dynamic_secret_type: dynamic_secret_type
          metadata: metadata
          last_admin_rotation: 9
          db_max_open_conns: db_max_open_conns
          admin_rotation_interval_days: 0
          ssl_connection_certificate: ssl_connection_certificate
          oracle_creation_statements: oracle_creation_statements
          mssql_creation_statements: mssql_creation_statements
          password: password
          sf_user_role: sf_user_role
          privileged_user: privileged_user
          ldap_certificate: ldap_certificate
          gcp_role_bindings:
            key:
            - gcp_role_bindings
            - gcp_role_bindings
          ldap_url: ldap_url
          username_policy: username_policy
          gcp_token_scope: gcp_token_scope
          venafi_allowed_domains:
          - venafi_allowed_domains
          - venafi_allowed_domains
          warn_before_user_expiration_min: 1
          db_private_key: db_private_key
          fixed_user_only: fixed_user_only
          rabbitmq_server_password: rabbitmq_server_password
          aws_user_policies: aws_user_policies
          aws_role_arns: aws_role_arns
          active: true
          item_targets_assoc:
          - assoc_id: assoc_id
            target_name: target_name
            target_type: target_type
            attributes:
              key: attributes
            target_id: 6
          - assoc_id: assoc_id
            target_name: target_name
            target_type: target_type
            attributes:
              key: attributes
            target_id: 6
          chef_server_username: chef_server_username
          tags:
          - tags
          - tags
          mongodb_custom_data: mongodb_custom_data
          k8s_service_account: k8s_service_account
          chef_skip_ssl: true
          k8s_cluster_endpoint: k8s_cluster_endpoint
          azure_client_secret: azure_client_secret
          azure_user_groups_obj_id: azure_user_groups_obj_id
          gcp_token_type: gcp_token_type
          access_token_manager_id: access_token_manager_id
          gcp_token_lifetime: gcp_token_lifetime
          user_name: user_name
          rabbitmq_user_vhost: rabbitmq_user_vhost
          mongodb_username: mongodb_username
          postgres_revocation_statements: postgres_revocation_statements
          venafi_signer_key_name: venafi_signer_key_name
          should_stop: should_stop
          artifactory_token_audience: artifactory_token_audience
          mongodb_atlas_api_public_key: mongodb_atlas_api_public_key
          github_installation_token_permissions:
            key: github_installation_token_permissions
          timeout_seconds: 4
          eks_assume_role: eks_assume_role
          db_max_idle_conns: db_max_idle_conns
          admin_name: admin_name
          rabbitmq_server_user: rabbitmq_server_user
          venafi_api_key: venafi_api_key
          mongodb_host_port: mongodb_host_port
          gke_cluster_ca_certificate: gke_cluster_ca_certificate
          k8s_bearer_token: k8s_bearer_token
          azure_resource_name: azure_resource_name
          cassandra_creation_statements: cassandra_creation_statements
          failure_message: failure_message
          db_private_key_passphrase: db_private_key_passphrase
          rabbitmq_user_read_permission: rabbitmq_user_read_permission
          azure_client_id: azure_client_id
          mongodb_default_auth_db: mongodb_default_auth_db
          mongodb_atlas_project_id: mongodb_atlas_project_id
          payload: payload
          redshift_creation_statements: redshift_creation_statements
          enforce_replay_prevention: true
          ldap_audience: ldap_audience
          redirect_uris:
          - redirect_uris
          - redirect_uris
          venafi_allow_subdomains: true
          aws_user_console_access: true
          azure_resource_group_name: azure_resource_group_name
          user_principal_name: user_principal_name
          azure_subscription_id: azure_subscription_id
          gcp_key_algo: gcp_key_algo
          venafi_zone: venafi_zone
          github_installation_token_repositories:
          - github_installation_token_repositories
          - github_installation_token_repositories
          gcp_service_account_key: gcp_service_account_key
          gcp_service_account_type: gcp_service_account_type
          session_extension_warn_interval_min: 2
          venafi_store_private_key: true
          eks_cluster_endpoint: eks_cluster_endpoint
          gke_service_account_key: gke_service_account_key
          mongodb_uri_options: mongodb_uri_options
          github_app_private_key: github_app_private_key
          gke_service_account_name: gke_service_account_name
          mysql_creation_statements: mysql_creation_statements
          github_installation_id: 5
          k8s_allowed_namespaces: k8s_allowed_namespaces
          rabbitmq_server_uri: rabbitmq_server_uri
          chef_server_access_mode: chef_server_access_mode
          rabbitmq_user_conf_permission: rabbitmq_user_conf_permission
          is_fixed_user: is_fixed_user
          sf_account: sf_account
          secure_remote_access_details:
            schema: schema
            web_proxy: true
            bastion_ssh: bastion_ssh
            isolated: true
            ssh_private_key: true
            allow_port_forwarding: true
            is_web: true
            endpoint: endpoint
            native: true
            enable: true
            host:
            - host
            - host
            dashboard_url: dashboard_url
            bastion_issuer: bastion_issuer
            ssh_user: ssh_user
            is_cli: true
            use_internal_bastion: true
            rdp_user: rdp_user
            url: url
            account_id: account_id
            db_name: db_name
            allow_providing_external_username: true
            domain: domain
            bastion_api: bastion_api
            rotate_after_disconnect: true
            category: category
            region: region
            ssh_password: true
            bastion_issuer_id: 9
          chef_server_host_name: chef_server_host_name
          k8s_role_type: k8s_role_type
          mongodb_is_atlas: true
          eks_cluster_ca_certificate: eks_cluster_ca_certificate
          rotate_sync_url: rotate_sync_url
          chef_server_url: chef_server_url
          aws_user_groups: aws_user_groups
          azure_tenant_id: azure_tenant_id
          jwks_url: jwks_url
          k8s_namespace: k8s_namespace
          user_password: user_password
          venafi_sign_using_akeyless_pki: true
          dynamic_secret_key: dynamic_secret_key
          chef_server_key: chef_server_key
          implementation_type: implementation_type
          gcp_tmp_service_account_name: gcp_tmp_service_account_name
          issuer: issuer
          github_app_id: 1
          ldap_bind_dn: ldap_bind_dn
          k8s_temp_role_definition:
          - 7
          - 7
          admin_pwd: admin_pwd
          azure_fixed_user_only: true
          azure_user_roles_template_id: azure_user_roles_template_id
          aws_access_mode: aws_access_mode
          username_length: 7
          authorization_port: authorization_port
          db_host_name: db_host_name
          ldap_user_dn: ldap_user_dn
          azure_fixed_user_name_sub_claim_key: azure_fixed_user_name_sub_claim_key
          delete_protection: true
          db_name: db_name
          k8s_role_name: k8s_role_name
          db_port: db_port
          artifactory_base_url: artifactory_base_url
          create_sync_url: create_sync_url
          aws_session_token: aws_session_token
          jwks: jwks
          hanadb_revocation_statements: hanadb_revocation_statements
          db_isolation_level: db_isolation_level
          ssl_connection_mode: true
          mongodb_roles: mongodb_roles
          mongodb_db_name: mongodb_db_name
          eks_access_key_id: eks_access_key_id
          venafi_base_url: venafi_base_url
          user_ttl: user_ttl
          ping_url: ping_url
          ldap_token_expiration: ldap_token_expiration
          venafi_use_tpp: true
          mongodb_password: mongodb_password
          aws_secret_access_key: aws_secret_access_key
          mongodb_atlas_api_private_key: mongodb_atlas_api_private_key
          postgres_creation_statements: postgres_creation_statements
          password_policy: password_policy
          artifactory_admin_username: artifactory_admin_username
          restricted_scopes:
          - restricted_scopes
          - restricted_scopes
          scopes:
          - scopes
          - scopes
          sf_warehouse_name: sf_warehouse_name
          artifactory_token_scope: artifactory_token_scope
          k8s_dynamic_mode: true
          revoke_sync_url: revoke_sync_url
          host_port: host_port
          enable_admin_rotation: true
          client_authentication_type: client_authentication_type
          mongodb_uri_connection: mongodb_uri_connection
          db_user_name: db_user_name
          eks_region: eks_region
          artifactory_admin_apikey: artifactory_admin_apikey
          azure_app_object_id: azure_app_object_id
          ldap_bind_password: ldap_bind_password
          subject_dn: subject_dn
          externally_provided_user: externally_provided_user
          db_server_certificates: db_server_certificates
          db_server_name: db_server_name
          venafi_tpp_username: venafi_tpp_username
          azure_user_portal_access: true
          venafi_root_first_in_chain: true
          venafi_auto_generated_folder: venafi_auto_generated_folder
          db_pwd: db_pwd
          signing_algorithm: signing_algorithm
          administrative_port: administrative_port
          github_installation_token_repositories_ids:
          - 5
          - 5
          gcp_service_account_email: gcp_service_account_email
          hanadb_creation_statements: hanadb_creation_statements
          password_length: 3
          dynamic_secret_name: dynamic_secret_name
          aws_user_programmatic_access: true
          rabbitmq_user_write_permission: rabbitmq_user_write_permission
          rabbitmq_user_tags: rabbitmq_user_tags
          venafi_tpp_password: venafi_tpp_password
          ldap_user_attr: ldap_user_attr
          use_gw_cloud_identity: true
          azure_user_programmatic_access: true
          k8s_cluster_ca_certificate: k8s_cluster_ca_certificate
          eks_secret_access_key: eks_secret_access_key
          grant_types:
          - grant_types
          - grant_types
          github_base_url: github_base_url
          groups: groups
          chef_organizations: chef_organizations
          dynamic_secret_id: 6
          mssql_revocation_statements: mssql_revocation_statements
          chef_server_port: chef_server_port
          github_repository_path: github_repository_path
          aws_access_key_id: aws_access_key_id
          aws_region: aws_region
          eks_cluster_name: eks_cluster_name
          gke_cluster_name: gke_cluster_name
          k8s_temp_role_binding_definition:
          - 2
          - 2
          host_name: host_name
      properties:
        producer_details:
          $ref: '#/components/schemas/DSProducerDetails'
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client/commands
