openapi: 3.2.0
info:
  contact:
    email: support@akeyless.io
    name: Akeyless
    url: http://akeyless.io
  description: The purpose of this application is to provide access to Akeyless API.
  title: Akeyless Get Target API
  version: '2.0'
servers:
- url: https://api.akeyless.io/
tags:
- name: Get Target
paths:
  /get-target:
    post:
      operationId: getTarget
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/getTarget'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Target'
          description: getTargetResponse wraps response body.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JSONError'
          description: 'errorResponse wraps any error to return it as a JSON object with one "error"

            field.'
      tags:
      - Get Target
      x-codegen-request-body-name: body
      summary: Get target
      x-summary-source: derived
components:
  schemas:
    JSONError:
      properties:
        error:
          type: string
          x-go-name: Err
      title: JSONError wraps an error with JSON object.
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client
    Target:
      example:
        credentials_less: true
        target_items_assoc:
        - cluster_id: 1
          assoc_id: assoc_id
          item_type: item_type
          attributes:
            key: attributes
          item_name: item_name
          relationship: relationship
        - cluster_id: 1
          assoc_id: assoc_id
          item_type: item_type
          attributes:
            key: attributes
          item_name: item_name
          relationship: relationship
        target_name: target_name
        access_date: 2000-01-23 04:56:07+00:00
        target_type: target_type
        target_id: 6
        creation_date: 2000-01-23 04:56:07+00:00
        is_access_request_enabled: true
        last_version: 0
        client_permissions:
        - client_permissions
        - client_permissions
        with_customer_fragment: true
        target_versions:
        - item_version_state: item_version_state
          with_customer_fragment: true
          access_date: 2000-01-23 04:56:07+00:00
          deletion_date: 2000-01-23 04:56:07+00:00
          modification_date: 2000-01-23 04:56:07+00:00
          protection_key_name: protection_key_name
          creation_date: 2000-01-23 04:56:07+00:00
          version: 3
          customer_fragment_id: customer_fragment_id
        - item_version_state: item_version_state
          with_customer_fragment: true
          access_date: 2000-01-23 04:56:07+00:00
          deletion_date: 2000-01-23 04:56:07+00:00
          modification_date: 2000-01-23 04:56:07+00:00
          protection_key_name: protection_key_name
          creation_date: 2000-01-23 04:56:07+00:00
          version: 3
          customer_fragment_id: customer_fragment_id
        modification_date: 2000-01-23 04:56:07+00:00
        attributes:
          key: '{}'
        comment: comment
        protection_key_name: protection_key_name
        access_request_status: access_request_status
      properties:
        access_date:
          format: date-time
          type: string
          x-go-name: AccessDate
        access_request_status:
          type: string
          x-go-name: AccessRequestStatus
        attributes:
          additionalProperties:
            type: object
          description: 'this is not "omitempty" since an empty value causes no update

            while an empty map will clear the attributes'
          type: object
          x-go-name: Attributes
        client_permissions:
          items:
            type: string
          type: array
          x-go-name: ClientPermissions
        comment:
          type: string
          x-go-name: Comment
        creation_date:
          format: date-time
          type: string
          x-go-name: CreationDate
        credentials_less:
          type: boolean
          x-go-name: CredentialsLess
        is_access_request_enabled:
          type: boolean
          x-go-name: IsAccessRequestEnabled
        last_version:
          format: int32
          type: integer
          x-go-name: LastVersion
        modification_date:
          format: date-time
          type: string
          x-go-name: ModificationDate
        protection_key_name:
          type: string
          x-go-name: ProtectionKeyName
        target_id:
          format: int64
          type: integer
          x-go-name: TargetID
        target_items_assoc:
          items:
            $ref: '#/components/schemas/TargetItemAssociation'
          type: array
          x-go-name: TargetItemsAssoc
        target_name:
          type: string
          x-go-name: TargetName
        target_type:
          title: TargetType ..
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
        target_versions:
          items:
            $ref: '#/components/schemas/ItemVersion'
          type: array
          x-go-name: TargetVersions
        with_customer_fragment:
          type: boolean
          x-go-name: WithCustomerFragment
      title: Target includes target details.
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
    ItemVersion:
      example:
        item_version_state: item_version_state
        with_customer_fragment: true
        access_date: 2000-01-23 04:56:07+00:00
        deletion_date: 2000-01-23 04:56:07+00:00
        modification_date: 2000-01-23 04:56:07+00:00
        protection_key_name: protection_key_name
        creation_date: 2000-01-23 04:56:07+00:00
        version: 3
        customer_fragment_id: customer_fragment_id
      properties:
        access_date:
          format: date-time
          type: string
          x-go-name: AccessDate
        creation_date:
          format: date-time
          type: string
          x-go-name: CreationDate
        customer_fragment_id:
          type: string
          x-go-name: CustomerFragmentId
        deletion_date:
          format: date-time
          type: string
          x-go-name: DeletionDate
        item_version_state:
          description: ItemState defines the different states an Item can be in
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
        modification_date:
          format: date-time
          type: string
          x-go-name: ModificationDate
        protection_key_name:
          type: string
          x-go-name: ProtectionKeyName
        version:
          format: int32
          type: integer
          x-go-name: Version
        with_customer_fragment:
          type: boolean
          x-go-name: WithCustomerFragment
      title: ItemVersion describes an item version in AKEYLESS.
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
    getTarget:
      properties:
        json:
          description: Set output format to JSON
          type: boolean
          x-go-name: Json
        name:
          description: Target name
          type: string
          x-go-name: TargetName
        show-versions:
          default: false
          description: Include all target versions in reply
          type: boolean
          x-go-name: ShowVersions
        token:
          description: Authentication token (see `/auth` and `/configure`)
          type: string
          x-go-name: Profile
        uid-token:
          description: The universal identity token, Required only for universal_identity authentication
          type: string
          x-go-name: UIDToken
      required:
      - name
      title: getTarget is a command that returns target.
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/client/commands
    TargetItemAssociation:
      description: 'TargetItemAssociation includes details of an association between a target

        and an item.'
      example:
        cluster_id: 1
        assoc_id: assoc_id
        item_type: item_type
        attributes:
          key: attributes
        item_name: item_name
        relationship: relationship
      properties:
        assoc_id:
          type: string
          x-go-name: AssociationID
        attributes:
          additionalProperties:
            type: string
          type: object
          x-go-name: Attributes
        cluster_id:
          format: int64
          type: integer
          x-go-name: GWClusterID
        item_name:
          type: string
          x-go-name: ItemName
        item_type:
          title: ItemType defines types supported by AKEYLESS.
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
        relationship:
          type: string
          x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
      type: object
      x-go-package: akeyless.io/akeyless-main-repo/go/src/infra/types
